#!/bin/bash
# Migration script from 3-model to 4-model architecture
# Generated by deep_researcher configuration validator

ENV_FILE=".env"

echo "Migrating to 4-model architecture..."

# Backup original file
cp "$ENV_FILE" "$ENV_FILE.backup.$(date +%Y%m%d_%H%M%S)"

# Add new 4-model variables based on legacy ones
if grep -q "^REASONING_MODEL_PROVIDER=" "$ENV_FILE"; then
    LEGACY_VALUE=$(grep "^REASONING_MODEL_PROVIDER=" "$ENV_FILE" | cut -d'=' -f2)
    if ! grep -q "^PLANNER_MODEL_PROVIDER=" "$ENV_FILE"; then
        echo "PLANNER_MODEL_PROVIDER=$LEGACY_VALUE" >> "$ENV_FILE"
        echo "Added PLANNER_MODEL_PROVIDER based on REASONING_MODEL_PROVIDER"
    fi
fi

if grep -q "^REASONING_MODEL=" "$ENV_FILE"; then
    LEGACY_VALUE=$(grep "^REASONING_MODEL=" "$ENV_FILE" | cut -d'=' -f2)
    if ! grep -q "^PLANNER_MODEL=" "$ENV_FILE"; then
        echo "PLANNER_MODEL=$LEGACY_VALUE" >> "$ENV_FILE"
        echo "Added PLANNER_MODEL based on REASONING_MODEL"
    fi
fi

if grep -q "^MAIN_MODEL_PROVIDER=" "$ENV_FILE"; then
    LEGACY_VALUE=$(grep "^MAIN_MODEL_PROVIDER=" "$ENV_FILE" | cut -d'=' -f2)
    if ! grep -q "^SUMMARISER_MODEL_PROVIDER=" "$ENV_FILE"; then
        echo "SUMMARISER_MODEL_PROVIDER=$LEGACY_VALUE" >> "$ENV_FILE"
        echo "Added SUMMARISER_MODEL_PROVIDER based on MAIN_MODEL_PROVIDER"
    fi
fi

if grep -q "^MAIN_MODEL=" "$ENV_FILE"; then
    LEGACY_VALUE=$(grep "^MAIN_MODEL=" "$ENV_FILE" | cut -d'=' -f2)
    if ! grep -q "^SUMMARISER_MODEL=" "$ENV_FILE"; then
        echo "SUMMARISER_MODEL=$LEGACY_VALUE" >> "$ENV_FILE"
        echo "Added SUMMARISER_MODEL based on MAIN_MODEL"
    fi
fi

if grep -q "^FAST_MODEL_PROVIDER=" "$ENV_FILE"; then
    LEGACY_VALUE=$(grep "^FAST_MODEL_PROVIDER=" "$ENV_FILE" | cut -d'=' -f2)
    if ! grep -q "^WRITER_MODEL_PROVIDER=" "$ENV_FILE"; then
        echo "WRITER_MODEL_PROVIDER=$LEGACY_VALUE" >> "$ENV_FILE"
        echo "Added WRITER_MODEL_PROVIDER based on FAST_MODEL_PROVIDER"
    fi
fi

if grep -q "^FAST_MODEL=" "$ENV_FILE"; then
    LEGACY_VALUE=$(grep "^FAST_MODEL=" "$ENV_FILE" | cut -d'=' -f2)
    if ! grep -q "^WRITER_MODEL=" "$ENV_FILE"; then
        echo "WRITER_MODEL=$LEGACY_VALUE" >> "$ENV_FILE"
        echo "Added WRITER_MODEL based on FAST_MODEL"
    fi
fi

echo "Migration completed!"
echo "Please review the updated .env file and remove legacy variables if desired."
echo "Backup saved as: $ENV_FILE.backup.<timestamp>"