"""
Agent used to crawl a website and return the results.

The CrawlAgent takes as input a string in the format of AgentTask.model_dump_json(), or can take a simple starting url string as input

The Agent then:
1. Uses the crawl_website tool to crawl the website
2. Writes a comprehensive summary of the crawled contents
3. Includes citations/URLs in brackets next to information sources
4. Returns the formatted summary with enhanced metadata
"""

from agents import function_tool
from ...tools.crawl_website import crawl_website
from . import ToolAgentOutput
from ...llm_config import LLMConfig, model_supports_structured_output
from ..baseclass import ResearchAgent
from ..utils.parse_output import create_type_parser
from ..utils.hierarchical_summariser import HierarchicalSummariser
from ..utils.outlines_schemas import EnhancedToolAgentOutput, summarise_crawled_content
from ..utils.outlines_templates import (
    render_crawl_summary_prompt,
    render_legacy_crawl_summary_prompt,
    extract_crawl_params
)
import time
from typing import Optional, Dict, Any

# Graceful Outlines import for dual-path architecture
try:
    import outlines
    OUTLINES_AVAILABLE = True
except ImportError:
    outlines = None
    OUTLINES_AVAILABLE = False
    print("[CrawlAgent] Outlines not available, using legacy parsing only")


# Dynamic instructions will be generated by template system
# Legacy fallback instructions for non-Outlines path
LEGACY_INSTRUCTIONS = """
You are the SiteCrawlerAgent. You receive an AgentTask containing:
- gap: the knowledge gap to fill
- query: (optional) a short query string
- entity_website: the URL to start crawling

Your task is to crawl the website and return relevant information. You have access to the crawl_website tool.

You MUST respond with valid JSON in exactly this format:

{
  "output": "A summary of relevant information found on the website that addresses the knowledge gap",
  "sources": ["https://url1.com", "https://url2.com", "..."]
}

Use the crawl_website tool to gather information from the target website, then summarize the key findings that address the knowledge gap.
"""


class OutlinesCrawlAgent(ResearchAgent):
    """CrawlAgent with Outlines structured generation and dual-path architecture"""
    
    def __init__(self, config: LLMConfig, crawl_tool, summariser):
        from ..utils.model_role_registry import ModelRole
        selected_model = config.get_model_for_role(ModelRole.SUMMARISER)  # Fixed: use SUMMARISER role
        
        # Initialize with legacy instructions for fallback
        super().__init__(
            name="SiteCrawlerAgent",
            instructions=LEGACY_INSTRUCTIONS,
            tools=[crawl_tool],
            model=selected_model,
            summariser=summariser,
            output_type=None,  # Will be set by path selection
            output_parser=None   # Will be set by path selection
        )
        
        self.config = config
        self.supports_structured = model_supports_structured_output(selected_model)
        self.outlines_generator = None
        
        # Initialize Outlines generator if supported and available
        if self.supports_structured and OUTLINES_AVAILABLE:
            try:
                schema = EnhancedToolAgentOutput.model_json_schema()
                self.outlines_generator = outlines.Generator(selected_model, schema)
                print(f"[CrawlAgent] Outlines generator initialized for {selected_model}")
            except Exception as e:
                print(f"[CrawlAgent] Outlines initialization failed: {e}, falling back to legacy")
                self.supports_structured = False
        elif self.supports_structured and not OUTLINES_AVAILABLE:
            print("[CrawlAgent] Model supports structured output but Outlines not available, using legacy")
            self.supports_structured = False
        
        # Set output handling based on path
        if self.supports_structured:
            self.output_type = EnhancedToolAgentOutput
            # No output_parser for structured path
        else:
            # Legacy path uses output_parser, not output_type
            self.output_parser = create_type_parser(ToolAgentOutput)
    
    async def run_implementation(self, input_data: str) -> Dict[str, Any]:
        """Enhanced run implementation with dual-path architecture"""
        start_time = time.time()
        
        # Extract parameters from input
        params = extract_crawl_params(input_data)
        knowledge_gap = params["knowledge_gap"]
        target_website = params["target_website"]
        search_query = params["search_query"]
        
        # Execute crawl website tool
        crawled_content = ""
        for tool in self.tools:
            if hasattr(tool, 'name') and 'crawl' in tool.name.lower():
                try:
                    crawled_content = await tool.func(target_website)
                    break
                except Exception as e:
                    print(f"[CrawlAgent] Tool execution failed: {e}")
                    crawled_content = f"Crawl failed: {e}"
        
        # Use HierarchicalSummariser for large content
        if len(crawled_content) > 2000 and self.summariser:
            try:
                summarized = await self.summariser.summarise_large_content(
                    content=crawled_content,
                    context=f"Knowledge gap: {knowledge_gap}"
                )
                crawled_content = summarized.get("final_summary", crawled_content)
                print(f"[CrawlAgent] Content summarized: {len(crawled_content)} chars")
            except Exception as e:
                print(f"[CrawlAgent] Summarization failed: {e}, using raw content")
        
        # Dual-path execution
        if self.supports_structured and self.outlines_generator:
            return await self._structured_path(knowledge_gap, target_website, crawled_content, search_query, start_time)
        else:
            return await self._legacy_path(knowledge_gap, target_website, crawled_content, search_query, start_time)
    
    async def _structured_path(self, knowledge_gap: str, target_website: str, crawled_content: str,
                             search_query: Optional[str], start_time: float) -> Dict[str, Any]:
        """Outlines structured generation path"""
        try:
            # Generate structured prompt
            prompt = render_crawl_summary_prompt(
                knowledge_gap=knowledge_gap,
                target_website=target_website,
                crawled_content=crawled_content,
                search_query=search_query
            )
            
            # Generate structured response
            response = self.outlines_generator.generate(prompt)
            
            # Create enhanced output with metadata
            processing_time = int((time.time() - start_time) * 1000)
            result = EnhancedToolAgentOutput(
                output=response.get("output", ""),
                sources=response.get("sources", [target_website]),
                processing_method="structured",
                confidence=0.95,  # High confidence for structured output
                processing_time_ms=processing_time
            )
            
            print(f"[CrawlAgent] Structured generation completed in {processing_time}ms")
            return result.model_dump()
            
        except Exception as e:
            print(f"[CrawlAgent] Structured generation failed: {e}, falling back to legacy")
            return await self._legacy_path(knowledge_gap, target_website, crawled_content, search_query, start_time)
    
    async def _legacy_path(self, knowledge_gap: str, target_website: str, crawled_content: str,
                          search_query: Optional[str], start_time: float) -> Dict[str, Any]:
        """Legacy parsing path with enhanced output"""
        try:
            # Generate legacy prompt
            prompt = render_legacy_crawl_summary_prompt(
                knowledge_gap=knowledge_gap,
                target_website=target_website,
                crawled_content=crawled_content,
                search_query=search_query
            )
            
            # Generate response using model (compatible with agents library)
            messages = [{"role": "user", "content": prompt}]
            response = await self.model(messages)
            raw_output = response.content.strip()
            
            # Parse legacy response
            if self.output_parser:
                parsed = self.output_parser.parse(raw_output)
            else:
                # Simple JSON parsing fallback
                import json
                parsed = json.loads(raw_output)
            
            # Convert to enhanced output with metadata
            processing_time = int((time.time() - start_time) * 1000)
            result = EnhancedToolAgentOutput(
                output=parsed.get("output", ""),
                sources=parsed.get("sources", [target_website]),
                processing_method="legacy",
                confidence=0.85,  # Lower confidence for legacy parsing
                processing_time_ms=processing_time
            )
            
            print(f"[CrawlAgent] Legacy processing completed in {processing_time}ms")
            return result.model_dump()
            
        except Exception as e:
            print(f"[CrawlAgent] Legacy processing failed: {e}")
            # Fallback error response
            return {
                "output": f"Crawl processing failed: {e}",
                "sources": [target_website],
                "processing_method": "error_fallback",
                "confidence": 0.0,
                "processing_time_ms": int((time.time() - start_time) * 1000)
            }


def init_crawl_agent(config: LLMConfig) -> ResearchAgent:
    # Use SUMMARISER model role for consistency with SearchAgent
    from ..utils.model_role_registry import ModelRole
    selected_model = config.get_model_for_role(ModelRole.SUMMARISER)
    print(f"[init_crawl_agent] summariser_model={selected_model!r}", flush=True)

    # Add hierarchical summariser for large crawled content
    summariser = HierarchicalSummariser(
        fast_model=config.fast_model,
        slow_model=config.main_model,
        chunk_size=1000,  # Larger chunks for crawled content
        overlap=150
    )

    # Create a proper function to decorate
    def crawl_website_func(url: str):
        """Crawl a website starting from a given URL and return scraped content."""
        return crawl_website(url)

    crawl_tool = function_tool(
        name_override="crawl_website",
        description_override="Crawl a website starting from a given URL and return scraped content."
    )(crawl_website_func)
    
    # Expose inner function for tests
    crawl_tool.func = crawl_website_func
    crawl_tool.__name__ = crawl_website_func.__name__
    
    print(f"[init_crawl_agent] registered tool: {getattr(crawl_tool, 'name', 'crawl_website')!r}", flush=True)
    
    # Return enhanced agent with dual-path architecture
    return OutlinesCrawlAgent(config, crawl_tool, summariser)
