# deep_researcher/agents/tool_agents/search_agent.py

from agents import function_tool
from ...tools.web_search import create_web_search_tool
from ...llm_config import LLMConfig, model_supports_structured_output, get_base_url
from . import ToolAgentOutput
from ..baseclass import ResearchAgent
from ..utils.parse_output import create_type_parser
from ..utils.hierarchical_summariser import HierarchicalSummariser
from ..utils.outlines_schemas import EnhancedToolAgentOutput, summarise_search_results
from ..utils.outlines_templates import (
    render_search_summary_prompt,
    render_legacy_search_summary_prompt, 
    extract_search_params
)
import time
from typing import Optional, Dict, Any

# Graceful Outlines import for dual-path architecture
try:
    import outlines
    OUTLINES_AVAILABLE = True
except ImportError:
    outlines = None
    OUTLINES_AVAILABLE = False
    print("[SearchAgent] Outlines not available, using legacy parsing only")

# Dynamic instructions will be generated by template system
# Legacy fallback instructions for non-Outlines path
LEGACY_INSTRUCTIONS = """
You are the WebSearchAgent. You receive an AgentTask containing:
- gap: the knowledge gap to fill  
- query: a 3-6 word search string  
- entity_website: (optional) a domain to bias your search

Your task is to perform a web search and return the results. You have access to the web_search tool.

IMPORTANT: You must first use the web_search tool to find information, then provide your final response.

After using the web_search tool, you MUST respond with valid JSON in exactly this format:

{
  "output": "A summary of your search findings that addresses the knowledge gap",
  "sources": ["https://url1.com", "https://url2.com", "..."]
}

Steps:
1. Use the web_search tool with the provided query
2. Analyze the search results
3. Write a summary that addresses the knowledge gap
4. List the source URLs from the search results
5. Format your response as the JSON above
"""



class OutlinesSearchAgent(ResearchAgent):
    """SearchAgent with Outlines structured generation and dual-path architecture"""
    
    def __init__(self, config: LLMConfig, web_search_tool, summariser):
        from ..utils.model_role_registry import ModelRole
        selected_model = config.get_model_for_role(ModelRole.SUMMARISER)
        
        # Initialize with legacy instructions for fallback
        super().__init__(
            name="WebSearchAgent",
            instructions=LEGACY_INSTRUCTIONS,
            tools=[web_search_tool],
            model=selected_model,
            summariser=summariser,
            output_type=None,  # Will be set by path selection
            output_parser=None   # Will be set by path selection
        )
        
        self.config = config
        self.supports_structured = model_supports_structured_output(selected_model)
        self.outlines_generator = None
        
        # Initialize Outlines generator if supported and available
        if self.supports_structured and OUTLINES_AVAILABLE:
            try:
                schema = EnhancedToolAgentOutput.model_json_schema()
                self.outlines_generator = outlines.Generator(selected_model, schema)
                print(f"[SearchAgent] Outlines generator initialized for {selected_model}")
            except Exception as e:
                print(f"[SearchAgent] Outlines initialization failed: {e}, falling back to legacy")
                self.supports_structured = False
        elif self.supports_structured and not OUTLINES_AVAILABLE:
            print("[SearchAgent] Model supports structured output but Outlines not available, using legacy")
            self.supports_structured = False
        
        # Set output handling based on path
        if self.supports_structured:
            self.output_type = EnhancedToolAgentOutput
            # No output_parser for structured path
        else:
            # Legacy path uses output_parser, not output_type
            self.output_parser = create_type_parser(ToolAgentOutput)
    
    async def run_implementation(self, input_data: str) -> Dict[str, Any]:
        """Enhanced run implementation with dual-path architecture"""
        start_time = time.time()
        
        # Extract parameters from input
        params = extract_search_params(input_data)
        knowledge_gap = params["knowledge_gap"]
        search_query = params["search_query"]
        entity_website = params["entity_website"]
        
        # Execute web search tool
        search_results = ""
        for tool in self.tools:
            if hasattr(tool, 'name') and 'search' in tool.name.lower():
                try:
                    search_results = await tool.func(search_query)
                    break
                except Exception as e:
                    print(f"[SearchAgent] Tool execution failed: {e}")
                    search_results = f"Search failed: {e}"
        
        # Dual-path execution
        if self.supports_structured and self.outlines_generator:
            return await self._structured_path(knowledge_gap, search_query, search_results, entity_website, start_time)
        else:
            return await self._legacy_path(knowledge_gap, search_query, search_results, entity_website, start_time)
    
    async def _structured_path(self, knowledge_gap: str, search_query: str, search_results: str, 
                             entity_website: Optional[str], start_time: float) -> Dict[str, Any]:
        """Outlines structured generation path"""
        try:
            # Generate structured prompt
            prompt = render_search_summary_prompt(
                knowledge_gap=knowledge_gap,
                search_query=search_query,
                search_results=search_results,
                entity_website=entity_website
            )
            
            # Generate structured response
            response = self.outlines_generator.generate(prompt)
            
            # Create enhanced output with metadata
            processing_time = int((time.time() - start_time) * 1000)
            result = EnhancedToolAgentOutput(
                output=response.get("output", ""),
                sources=response.get("sources", []),
                processing_method="structured",
                confidence=0.95,  # High confidence for structured output
                processing_time_ms=processing_time
            )
            
            print(f"[SearchAgent] Structured generation completed in {processing_time}ms")
            return result.model_dump()
            
        except Exception as e:
            print(f"[SearchAgent] Structured generation failed: {e}, falling back to legacy")
            return await self._legacy_path(knowledge_gap, search_query, search_results, entity_website, start_time)
    
    async def _legacy_path(self, knowledge_gap: str, search_query: str, search_results: str,
                          entity_website: Optional[str], start_time: float) -> Dict[str, Any]:
        """Legacy parsing path with enhanced output"""
        try:
            # Generate legacy prompt
            prompt = render_legacy_search_summary_prompt(
                knowledge_gap=knowledge_gap,
                search_query=search_query,
                search_results=search_results,
                entity_website=entity_website
            )
            
            # Generate response using model (compatible with agents library)
            messages = [{"role": "user", "content": prompt}]
            response = await self.model(messages)
            raw_output = response.content.strip()
            
            # Parse legacy response
            if self.output_parser:
                parsed = self.output_parser.parse(raw_output)
            else:
                # Simple JSON parsing fallback
                import json
                parsed = json.loads(raw_output)
            
            # Convert to enhanced output with metadata
            processing_time = int((time.time() - start_time) * 1000)
            result = EnhancedToolAgentOutput(
                output=parsed.get("output", ""),
                sources=parsed.get("sources", []),
                processing_method="legacy",
                confidence=0.85,  # Lower confidence for legacy parsing
                processing_time_ms=processing_time
            )
            
            print(f"[SearchAgent] Legacy processing completed in {processing_time}ms")
            return result.model_dump()
            
        except Exception as e:
            print(f"[SearchAgent] Legacy processing failed: {e}")
            # Fallback error response
            return {
                "output": f"Search processing failed: {e}",
                "sources": [],
                "processing_method": "error_fallback",
                "confidence": 0.0,
                "processing_time_ms": int((time.time() - start_time) * 1000)
            }


def init_search_agent(config: LLMConfig) -> ResearchAgent:
    # choose the right model & search provider
    from ..utils.model_role_registry import ModelRole
    selected_model = config.get_model_for_role(ModelRole.SUMMARISER)
    print(f"[init_search_agent] search_provider={config.search_provider!r}, summariser_model={selected_model!r}", flush=True)
    provider_base_url = get_base_url(selected_model)
    if config.search_provider == "openai" and 'openai.com' not in provider_base_url:
        raise ValueError(f"SEARCH_PROVIDER='openai' but using non-OpenAI model {selected_model}")
    
    # Create the web search tool (already wrapped as FunctionTool)
    web_search_tool = create_web_search_tool(config)

    # Add hierarchical summariser for large content
    summariser = HierarchicalSummariser(
        fast_model=config.fast_model,
        slow_model=config.main_model,
        chunk_size=800,
        overlap=100
    )

    print(f"[init_search_agent] registered tool: {getattr(web_search_tool, 'name', 'web_search')!r}", flush=True)
    
    # Return enhanced agent with dual-path architecture
    return OutlinesSearchAgent(config, web_search_tool, summariser)
